language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC1

jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - scripts/travis-publish.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

notifications:
  irc:
    channels:
      - "chat.freenode.net#spire-math"
    on_success: change
    on_failure: always

sudo: false
